### ISSUE TITLE
[Talent Profile] Web App General View

### ISSUE THREAD

**Issue by idzharin** [glovory/werk-b2c-webapp#13]
## Tasks:
- [ ] [Privacy Settings](https://www.notion.so/glovory/Talent-Profile-Privacy-Settings-11d1fe0ce8d14ae99d759326d249363d)
- [ ] Public [View](https://www.notion.so/glovory/Talent-Profile-General-5a81ddb1a8b7458b85a24e9dbcaad918)
- [ ] Company [View](https://www.notion.so/glovory/Talent-Profile-General-98f28e312dcf48a7985e22576e447816)

## Team Assignment:
- [ ]  () Design, @christantoputra-glovory 
- [ ]  () Test Case, @iqbal-wira 
- [ ]  () Backend,  
- [ ]  () Frontend, @M-Husein 
- [ ]  () Testing, @iqbal-wira 
- [ ]  () Deployment, @M-Husein 

## Requirement Document:
[General IA](https://www.notion.so/glovory/Master-Information-Architecture-048d85ccff414a5886170f2ca41406dc)

## Test Case:
N/A

## Prototype:
N/A

**Comment by christantoputra-glovory** [comment]
@iqbal-wira This task (design) is ready to QA

https://preview.uxpin.com/f359160a3b6e2c01457b87f2220d6347b29294ee#/pages/159859136/simulate/no-panels?mode=i
