### ISSUE TITLE
[Talent Profile] Web App Education

### ISSUE THREAD

**Issue by idzharin** [glovory/werk-b2c-webapp#18]
## Tasks:
- [ ] [Education](https://www.notion.so/glovory/Talent-Profile-Education-22bd870861c84163854b647be17a7476)

## Team Assignment:
- [ ]  () Design, @christantoputra-glovory 
- [ ]  () Test Case, @iqbal-wira 
- [ ]  () Backend, @jaycakep 
- [ ]  () Frontend, @M-Husein  
- [ ]  () Testing, @iqbal-wira 
- [ ]  () Deployment, @M-Husein 

## Requirement Document:
[Information Architecture V1](https://www.notion.so/glovory/Master-Information-Architecture-048d85ccff414a5886170f2ca41406dc)

## Test Case:
N/A

## Prototype:
N/A
