### ISSUE TITLE
[Talent Profile] Web App Work Experiences

### ISSUE THREAD

**Issue by idzharin** [glovory/werk-b2c-webapp#19]
## Tasks:
- [ ] [Work Experiences](https://www.notion.so/glovory/Talent-Profile-Work-Experiences-b51c45b06a3849df8909548c3c254104)

## Team Assignment:
- [ ]  () Design, @christantoputra-glovory 
- [ ]  () Test Case, @iqbal-wira 
- [ ]  () Backend, @jaycakep 
- [ ]  () Frontend, @M-Husein  
- [ ]  () Testing, @iqbal-wira 
- [ ]  () Deployment, @M-Husein 

## Requirement Document:
[Information Architecture V1](https://www.notion.so/glovory/Master-Information-Architecture-048d85ccff414a5886170f2ca41406dc)

## Test Case:
N/A

## Prototype:
N/A

**Comment by M-Husein** [comment]
Halo mas @iqbal-wira mas @idzharin 
This task almost done, only search feature not finish because I think need some addition from BE.
But this task can already be tested for other features except search.

Thanks.

**Comment by jaycakep** [comment]
> 

wich kind of search that I need to develop the function

**Comment by M-Husein** [comment]
I get some error, the message is "Index jobPosition, companyCountry, companyProvince, companyCity not found"
or not available.
Maybe need add Indexes.

**Comment by jaycakep** [comment]
> 

ok, done
