### ISSUE TITLE
[Talent Profile] Web App User Profile

### ISSUE THREAD

**Issue by idzharin** [glovory/werk-b2c-webapp#5]
## Tasks:
- [ ] User Profile
- [ ] User Profile - Settings
- [ ] User Profile - Privacy Policy, Terms & Condition, About Us

## Team Assignment:
- [ ]  () Design,
- [ ]  () Test Case, @iqbal-wira 
- [ ]  () Backend,  
- [ ]  () Frontend, @M-Husein 
- [ ]  () Testing, @iqbal-wira 
- [ ]  () Deployment, @M-Husein 

## Requirement Document:
- [User Profile](https://www.notion.so/glovory/Talent-Profile-User-Profile-7ec815832e7049f287b8c0f72e09a8a9)
- [User Profile - Settings](https://www.notion.so/glovory/Talent-Profile-User-Profile-820ceac07a8248cbb01aedfb3cb8e384)

## Test Case:
N/A

## Prototype:
N/A

**Comment by idzharin** [comment]
Mr @christantoputra-glovory, please provide the prototype link here

**Comment by christantoputra-glovory** [comment]
@idzharin 
UXPin preview:
https://preview.uxpin.com/f359160a3b6e2c01457b87f2220d6347b29294ee#/pages/159859136

**Comment by iqbal-wira** [comment]
Hi mas @idzharin , mba @CLuciana 
Here's the test case notion link
https://www.notion.so/glovory/Talent-Profile-Web-App-User-Profile-0b74a5ae6e4a49048acfb1235026f2ff
Thanks

**Comment by CLuciana** [comment]
> Hi mas @idzharin , mba @CLuciana Here's the test case notion link https://www.notion.so/glovory/Talent-Profile-Web-App-User-Profile-0b74a5ae6e4a49048acfb1235026f2ff Thanks

Thank you @iqbal-wira added to the task description ya.

Please check the test case while working on this task ya guys @M-Husein @jaycakep Thank you.

**Comment by M-Husein** [comment]
@iqbal-wira , @idzharin

https://staging.werk.id/

**Comment by M-Husein** [comment]
Hi mas @idzharin , mas @iqbal-wira 
This task is updated in:

1. Implement Unsplash API, View, Search & Choose image from unsplash source for setting background profile.
2. Edit & delete Background Profile
3. UI for Hard Skill
