### ISSUE TITLE
[Talent Profile] Web App User Profile Content Type

### ISSUE THREAD

**Issue by idzharin** [glovory/werk-b2c-webapp#6]
## Tasks:
- [ ] [Preferred Work Type](https://www.notion.so/glovory/Talent-Profile-Preferred-Work-Type-247a61365ecf44089437bc7eb78b0c7b)
- [ ] [Work Availability](https://www.notion.so/glovory/Talent-Profile-Work-Availability-0e81756509f3413497a5a39b704a9285)
- [ ] [Hard Skills](https://www.notion.so/glovory/Talent-Profile-Hard-Skills-5c6046a9acfa432489f0ceb8f627da79)
- [ ] [Soft Skills](https://www.notion.so/glovory/Talent-Profile-Soft-Skills-2447624b1bcc46ffb7eac4b6fb0ef8d8)

## Team Assignment:
- [ ]  () Design, @christantoputra-glovory 
- [ ]  () Test Case, @iqbal-wira 
- [ ]  () Backend,  
- [ ]  () Frontend, @M-Husein 
- [ ]  () Testing, @iqbal-wira 
- [ ]  () Deployment, @M-Husein 

## Requirement Document:
- [Information Architecture](https://www.notion.so/glovory/Master-Information-Architecture-048d85ccff414a5886170f2ca41406dc)

## Test Case:
N/A

## Prototype:
N/A

**Comment by iqbal-wira** [comment]
Hi mas @idzharin 
Here's the test case notion link
https://www.notion.so/glovory/Talent-Profile-Web-App-User-Profile-Content-Type-a241a22310f94859b8dfe0325404d903
Thanks
