### ISSUE TITLE
[General] Web App Preparation

### ISSUE THREAD

**Issue by idzharin** [glovory/werk-b2c-webapp#7]
## Tasks:
- [ ] [User Metronic 8 demo 7 Template](https://www.notion.so/glovory/Metronic-template-5755ffe020af4112967ad511aebcc081)
- [ ] [Use Roboto Font](https://www.notion.so/glovory/Roboto-font-type-f07ceaedaaba4340a66c76c0ed43d3da)
- [ ] [Add Internet Connection Status](https://www.notion.so/glovory/Internet-connection-status-4509e88910c1436ebaea97934e5e0dfe)
- [ ] [Add Component Failed Warning](https://www.notion.so/glovory/The-component-fails-to-load-data-from-the-backend-system-0f03607ccad74d599ca7bda2ca09b4fb)
- [ ] [Add Login Activity to User Activity Log](https://www.notion.so/glovory/User-activity-log-3c0c95d145784051a98944f0d5d852ce)
- [ ] [Implement Tolgee for the Translation Tools](https://www.notion.so/glovory/Tolgee-translation-ae7bcad646624077948738154e7f178d)
- [ ] Add Skeleton Loading per Component
- [ ] [Implement no Hover in every Component](https://www.notion.so/glovory/Hover-link-52472766cd6d4b8b9aaed215dbeb8e48)
- [ ] [Form Validation](https://www.notion.so/glovory/Form-validation-b893c6dcd9864b1ea2f87658cfb287ae)
- [ ] Integrate with MicroStack Authentication Service
- [ ] [Microservices architecture with standalone DB on each microservices ](https://www.notion.so/glovory/Microservices-architecture-with-standalone-DB-on-each-microservices-3c22bcb073344877bd89926288873cc6)

## Team Assignment:
- [ ]  () Designer, 
- [ ]  () Backend,  
- [ ]  () Frontend, @M-Husein 
- [ ]  () Deployment, @M-Husein 

## Requirement Document:
- [General Requirements](https://www.notion.so/glovory/General-Requirements-1096520f1b8a4e3aa0538ff7577491d3)

## Test Case:
N/A

## Prototype:
N/A
